version: '3'
services:

  nginx:
    hostname: nginx
    image: nginx:1.12.1
    ports:
      - 80:80
    networks:
      - lnpm
    depends_on:
      - flask
    volumes:
      - ./log:/log
      - ./tmp:/tmp
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: |
      bash -c '
      rm /etc/nginx/conf.d/default.conf
      /usr/sbin/nginx'

  flask:
    hostname: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    networks:
      - lnpm
    volumes:
      - ./tmp:/tmp
      - ./wwwroot:/app
      - ./log:/log
    # environment:
    #   - LANG=zh_CN.UTF-8
    command: |
      sh -c '
      pip3 install -r /app/requirements.txt
      cp /app/uwsgi.ini /etc/uwsgi/uwsgi.ini
      cp /app/supervisord.conf /etc/supervisord.conf
      /usr/bin/supervisord'

networks:
  lnpm:
